// Initial catalog used to seed an empty database.
// Image paths are served by this server from public/games (synced from the app stores).
import type { EventDoc, GameDoc, SkinDoc } from "./types.ts";

export const SEED_GAMES: GameDoc[] = [
  {
    _id: "codm",
    name: "Call of Duty: Mobile",
    publisher: "Activision",
    currency: "CP",
    tagline: "COD Points for Battle Pass, Lucky Draws & Mythic crates.",
    accent: "#f59e0b",
    icon: "/games/codm/icon.jpg",
    card: "/games/codm/shot-3.jpg",
    banner: "/games/codm/shot-2.jpg",
    playPackageId: "com.activision.callofduty.shooter",
    itunesTerm: "call of duty mobile",
    sort: 0,
    active: true,
    packs: [
      { id: "codm-80", amount: "80 CP", bonus: "", priceNgn: 1600, popular: false, sort: 0, active: true },
      { id: "codm-400", amount: "400 CP", bonus: "+40 bonus", priceNgn: 7500, popular: false, sort: 1, active: true },
      { id: "codm-800", amount: "800 CP", bonus: "+80 bonus", priceNgn: 14800, popular: true, sort: 2, active: true },
      { id: "codm-2000", amount: "2000 CP", bonus: "+260 bonus", priceNgn: 36500, popular: false, sort: 3, active: true },
      { id: "codm-5000", amount: "5000 CP", bonus: "+800 bonus", priceNgn: 74500, popular: false, sort: 4, active: true },
      { id: "codm-10800", amount: "10800 CP", bonus: "+1500 bonus", priceNgn: 145000, popular: false, sort: 5, active: true },
    ],
  },
  {
    _id: "mlbb",
    name: "Mobile Legends: Bang Bang",
    publisher: "Moonton",
    currency: "Diamonds",
    tagline: "Diamonds delivered straight to your MLBB user ID.",
    accent: "#38bdf8",
    icon: "/games/mlbb/icon.jpg",
    card: "/games/mlbb/shot-2.jpg",
    banner: "/games/mlbb/shot-4.jpg",
    playPackageId: "com.mobile.legends",
    itunesTerm: "mobile legends bang bang",
    sort: 1,
    active: true,
    packs: [
      { id: "mlbb-86", amount: "86 Diamonds", bonus: "", priceNgn: 1900, popular: false, sort: 0, active: true },
      { id: "mlbb-172", amount: "172 Diamonds", bonus: "", priceNgn: 3700, popular: false, sort: 1, active: true },
      { id: "mlbb-257", amount: "257 Diamonds", bonus: "", priceNgn: 5500, popular: false, sort: 2, active: true },
      { id: "mlbb-706", amount: "706 Diamonds", bonus: "", priceNgn: 14500, popular: true, sort: 3, active: true },
      { id: "mlbb-2195", amount: "2195 Diamonds", bonus: "", priceNgn: 43500, popular: false, sort: 4, active: true },
      { id: "mlbb-wdp", amount: "Weekly Diamond Pass", bonus: "", priceNgn: 2400, popular: false, sort: 5, active: true },
      { id: "mlbb-twilight", amount: "Twilight Pass", bonus: "", priceNgn: 12500, popular: false, sort: 6, active: true },
    ],
  },
  {
    _id: "pubgm",
    name: "PUBG Mobile",
    publisher: "Tencent / Level Infinite",
    currency: "UC",
    tagline: "Unknown Cash for Royale Pass, crates & collab draws.",
    accent: "#fbbf24",
    icon: "/games/pubgm/icon.jpg",
    card: "/games/pubgm/shot-3.jpg",
    banner: "/games/pubgm/shot-2.jpg",
    playPackageId: "com.tencent.ig",
    itunesTerm: "pubg mobile",
    sort: 2,
    active: true,
    packs: [
      { id: "pubgm-60", amount: "60 UC", bonus: "", priceNgn: 1500, popular: false, sort: 0, active: true },
      { id: "pubgm-325", amount: "325 UC", bonus: "+25 bonus", priceNgn: 7300, popular: false, sort: 1, active: true },
      { id: "pubgm-660", amount: "660 UC", bonus: "+60 bonus", priceNgn: 14500, popular: true, sort: 2, active: true },
      { id: "pubgm-1800", amount: "1800 UC", bonus: "+300 bonus", priceNgn: 36000, popular: false, sort: 3, active: true },
      { id: "pubgm-3850", amount: "3850 UC", bonus: "+550 bonus", priceNgn: 72000, popular: false, sort: 4, active: true },
      { id: "pubgm-8100", amount: "8100 UC", bonus: "+1200 bonus", priceNgn: 144000, popular: false, sort: 5, active: true },
    ],
  },
  {
    _id: "freefire",
    name: "Free Fire",
    publisher: "Garena",
    currency: "Diamonds",
    tagline: "FF Diamonds — instant top-up with just your player ID.",
    accent: "#fb923c",
    icon: "/games/freefire/icon.jpg",
    card: "/games/freefire/shot-2.jpg",
    banner: "/games/freefire/shot-2.jpg",
    playPackageId: "com.dts.freefireth",
    itunesTerm: "garena free fire",
    sort: 3,
    active: true,
    packs: [
      { id: "ff-100", amount: "100 Diamonds", bonus: "", priceNgn: 1300, popular: false, sort: 0, active: true },
      { id: "ff-310", amount: "310 Diamonds", bonus: "", priceNgn: 3900, popular: false, sort: 1, active: true },
      { id: "ff-520", amount: "520 Diamonds", bonus: "", priceNgn: 6400, popular: true, sort: 2, active: true },
      { id: "ff-1060", amount: "1060 Diamonds", bonus: "", priceNgn: 12800, popular: false, sort: 3, active: true },
      { id: "ff-2180", amount: "2180 Diamonds", bonus: "", priceNgn: 25500, popular: false, sort: 4, active: true },
      { id: "ff-5600", amount: "5600 Diamonds", bonus: "", priceNgn: 64000, popular: false, sort: 5, active: true },
    ],
  },
  {
    _id: "bloodstrike",
    name: "Blood Strike",
    publisher: "NetEase",
    currency: "Gold",
    tagline: "Strike Gold for the Strike Pass & collab events.",
    accent: "#f87171",
    icon: "/games/bloodstrike/icon.jpg",
    card: "/games/bloodstrike/shot-3.jpg",
    banner: "/games/bloodstrike/shot-3.jpg",
    playPackageId: "com.netease.newspike",
    itunesTerm: "blood strike netease",
    sort: 4,
    active: true,
    packs: [
      { id: "bs-300", amount: "300 Gold", bonus: "", priceNgn: 1500, popular: false, sort: 0, active: true },
      { id: "bs-980", amount: "980 Gold", bonus: "+80 bonus", priceNgn: 4800, popular: false, sort: 1, active: true },
      { id: "bs-1980", amount: "1980 Gold", bonus: "+180 bonus", priceNgn: 9500, popular: true, sort: 2, active: true },
      { id: "bs-3280", amount: "3280 Gold", bonus: "+380 bonus", priceNgn: 15800, popular: false, sort: 3, active: true },
      { id: "bs-6480", amount: "6480 Gold", bonus: "+880 bonus", priceNgn: 31000, popular: false, sort: 4, active: true },
    ],
  },
  {
    _id: "fcmobile",
    name: "EA SPORTS FC Mobile",
    publisher: "EA Sports",
    currency: "FC Points",
    tagline: "FC Points for packs, players & World Cup events.",
    accent: "#4ade80",
    icon: "/games/fcmobile/icon.jpg",
    card: "/games/fcmobile/shot-2.jpg",
    banner: "/games/fcmobile/shot-2.jpg",
    playPackageId: "com.ea.gp.fifamobile",
    itunesTerm: "ea sports fc mobile",
    sort: 5,
    active: true,
    packs: [
      { id: "fc-100", amount: "100 FC Points", bonus: "", priceNgn: 2200, popular: false, sort: 0, active: true },
      { id: "fc-500", amount: "500 FC Points", bonus: "", priceNgn: 10500, popular: false, sort: 1, active: true },
      { id: "fc-1050", amount: "1050 FC Points", bonus: "", priceNgn: 20500, popular: true, sort: 2, active: true },
      { id: "fc-2130", amount: "2130 FC Points", bonus: "", priceNgn: 41000, popular: false, sort: 3, active: true },
      { id: "fc-5580", amount: "5580 FC Points", bonus: "", priceNgn: 98000, popular: false, sort: 4, active: true },
    ],
  },
  {
    _id: "efootball",
    name: "eFootball 2026",
    publisher: "Konami",
    currency: "Coins",
    tagline: "eFootball Coins for Epic packs & national team campaigns.",
    accent: "#facc15",
    icon: "/games/efootball/icon.jpg",
    card: "/games/efootball/shot-2.jpg",
    banner: "/games/efootball/shot-2.jpg",
    playPackageId: "jp.konami.pesam",
    itunesTerm: "efootball",
    sort: 6,
    active: true,
    packs: [
      { id: "ef-130", amount: "130 Coins", bonus: "", priceNgn: 1600, popular: false, sort: 0, active: true },
      { id: "ef-550", amount: "550 Coins", bonus: "", priceNgn: 6500, popular: false, sort: 1, active: true },
      { id: "ef-1100", amount: "1100 Coins", bonus: "", priceNgn: 12800, popular: true, sort: 2, active: true },
      { id: "ef-2130", amount: "2130 Coins", bonus: "", priceNgn: 24500, popular: false, sort: 3, active: true },
      { id: "ef-3900", amount: "3900 Coins", bonus: "", priceNgn: 44000, popular: false, sort: 4, active: true },
    ],
  },
  {
    _id: "deltaforce",
    name: "Delta Force",
    publisher: "TiMi Studio Group",
    currency: "Delta Coins",
    tagline: "Delta Coins for operators, weapon mods & seasonal passes.",
    accent: "#a78bfa",
    icon: "/games/deltaforce/icon.jpg",
    card: "/games/deltaforce/shot-2.jpg",
    banner: "/games/deltaforce/shot-2.jpg",
    playPackageId: "com.proxima.dfm",
    itunesTerm: "delta force",
    sort: 7,
    active: true,
    packs: [
      { id: "df-60", amount: "60 Delta Coins", bonus: "", priceNgn: 1500, popular: false, sort: 0, active: true },
      { id: "df-320", amount: "320 Delta Coins", bonus: "+16 bonus", priceNgn: 7400, popular: false, sort: 1, active: true },
      { id: "df-640", amount: "640 Delta Coins", bonus: "+45 bonus", priceNgn: 14600, popular: true, sort: 2, active: true },
      { id: "df-1280", amount: "1280 Delta Coins", bonus: "+110 bonus", priceNgn: 29000, popular: false, sort: 3, active: true },
      { id: "df-3240", amount: "3240 Delta Coins", bonus: "+350 bonus", priceNgn: 72500, popular: false, sort: 4, active: true },
    ],
  },
];

export const SEED_SKINS: SkinDoc[] = [
  { _id: "skin-codm-p5", gameId: "codm", name: "Phantom Thieves Draw Bundle", rarity: "Mythic", priceNgn: 45000, image: "/games/codm/shot-2.jpg", sort: 0, active: true },
  { _id: "skin-codm-undead", gameId: "codm", name: "Undead Warlord Crate", rarity: "Legendary", priceNgn: 28500, image: "/games/codm/shot-4.jpg", sort: 1, active: true },
  { _id: "skin-mlbb-sf6", gameId: "mlbb", name: "SF6 Collab Skin Chest", rarity: "Legendary", priceNgn: 22000, image: "/games/mlbb/shot-3.jpg", sort: 2, active: true },
  { _id: "skin-mlbb-infernal", gameId: "mlbb", name: "Infernal Juggernaut Skin", rarity: "Epic", priceNgn: 14500, image: "/games/mlbb/shot-2.jpg", sort: 3, active: true },
  { _id: "skin-pubgm-naruto", gameId: "pubgm", name: "Naruto Shippuden Crate", rarity: "Mythic", priceNgn: 32000, image: "/games/pubgm/shot-3.jpg", sort: 4, active: true },
  { _id: "skin-bs-railgun", gameId: "bloodstrike", name: "Galactic Striker Vehicle Skin", rarity: "Epic", priceNgn: 9800, image: "/games/bloodstrike/shot-2.jpg", sort: 5, active: true },
  { _id: "skin-ff-anniv", gameId: "freefire", name: "9th Anniversary Bundle", rarity: "Epic", priceNgn: 8500, image: "/games/freefire/banner.jpg", sort: 6, active: true },
  { _id: "skin-df-colosseum", gameId: "deltaforce", name: "Colosseum Assault Operator Pack", rarity: "Legendary", priceNgn: 18000, image: "/games/deltaforce/shot-2.jpg", sort: 7, active: true },
];

export const SEED_EVENTS: EventDoc[] = [
  {
    _id: "ev-mlbb-sf6",
    gameId: "mlbb",
    title: "MLBB × Street Fighter 6",
    blurb: "Fighting Spirit Awakens — Ryu, Ken, Guile & Chun-Li collab skins land in the Exchange Shop.",
    image: "/games/mlbb/shot-4.jpg",
    tag: "Collab",
    endsAt: "2026-08-02T23:59:59+01:00",
    status: "live",
  },
  {
    _id: "ev-codm-p5",
    gameId: "codm",
    title: "CODM × Persona 5",
    blurb: "The Phantom Thieves take the battlefield. Themed Lucky Draws, login rewards & ranked drops.",
    image: "/games/codm/shot-2.jpg",
    tag: "Collab",
    endsAt: "2026-08-09T23:59:59+01:00",
    status: "live",
  },
  {
    _id: "ev-pubgm-naruto",
    gameId: "pubgm",
    title: "PUBG Mobile × Naruto Shippuden",
    blurb: "Kurama over Erangel. Naruto & Sasuke sets, Tailed-Beast emotes and collab crate discounts.",
    image: "/games/pubgm/shot-2.jpg",
    tag: "Collab",
    endsAt: "2026-07-28T23:59:59+01:00",
    status: "live",
  },
  {
    _id: "ev-bs-opm",
    gameId: "bloodstrike",
    title: "Blood Strike × One-Punch Man",
    blurb: "Saitama and Genos join the Strike. Collab pass, OPM finishers & limited lobby themes.",
    image: "/games/bloodstrike/shot-3.jpg",
    tag: "Collab",
    endsAt: "2026-07-24T23:59:59+01:00",
    status: "live",
  },
  {
    _id: "ev-ff-anniv",
    gameId: "freefire",
    title: "Free Fire 9th Anniversary",
    blurb: "9 years of Booyah! Free rewards all month, anniversary bundles & the Pilot Duck returns.",
    image: "/games/freefire/shot-2.jpg",
    tag: "Anniversary",
    endsAt: "2026-08-23T23:59:59+01:00",
    status: "live",
  },
  {
    _id: "ev-ef-nations",
    gameId: "efootball",
    title: "eFootball Nations Takeover",
    blurb: "National team campaigns with Epic international packs — Argentina, Brazil, Japan & more.",
    image: "/games/efootball/shot-2.jpg",
    tag: "Season",
    endsAt: "2026-07-31T23:59:59+01:00",
    status: "live",
  },
];
